main_app:
  image:
    repository: wzyla/cloud_tech
    imagePullPolicy: Always
    tag: "latest"
  env:
    # Nazwa bazy w PostgreSQL (taka sama ustawiona w bazie i w konfiguracji aplikacji laczacej sie z baza)
    DB_NAME: "db_name"
    # Nazwa serwisu kubernetesa dajacego dostep do PostgreSQL
    DB_HOST: "postgres-service"
    # Username w PostgreSQL (taki sam ustawiony w bazie i w konfiguracji aplikacji laczacej sie z baza)
    DB_USERNAME: "st_backend"
    # Haslo do PostgreSQL (takie samo ustawione w bazie i w konfiguracji aplikacji laczacej sie z baza)
    DB_PASSWORD: "abdj24AfwF#$1cw#4fq3d"
postgres:
  image:
    imagePullPolicy: Always
  PersistentVolume:
    # sciezka na maszynie lokalnej
    path: ""