apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
      - name: processing-container
        image: "{{ .Values.processing.image.repository }}:{{ .Values.processing.image.tag }}"
        imagePullPolicy: {{ .Values.processing.image.imagePullPolicy }}
        env:
        - name: ENCRYPTION_KEY
          value: {{ .Values.processing.env.ENCRYPTION_KEY | quote }}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: processing-service
spec:
  selector:
    app: processing
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: processing-network-policy
spec:
  podSelector:
    matchLabels:
      app: processing
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: rest-api
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: rest-api